"use client";

import { useCallback, useState } from "react";
import { DetectionContextInput } from "@/components/detection/DetectionContextInput";
import { DetectionModelSelect } from "@/components/detection/DetectionModelSelect";
import { DetectionResult } from "@/components/detection/DetectionResult";
import { DetectionStatus } from "@/components/detection/DetectionStatus";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { DemoControls } from "@/components/ui/DemoControls";
import { ErrorAlert } from "@/components/ui/ErrorAlert";
import { Spinner } from "@/components/ui/Spinner";
import { useDetectionTask } from "@/hooks/useDetectionTask";
import { useModels } from "@/hooks/useModels";
import { createTextDetection } from "@/lib/api";
import { TEXT_MAX_LENGTH, TEXT_MIN_LENGTH, USE_MOCKS } from "@/lib/constants";
import { mockCreateDetectionTask } from "@/lib/mocks/api";
import type { DemoOutcome } from "@/lib/mocks/demoData";
import { cn } from "@/lib/utils";

export default function TextDetectionPage() {
  const { models, status: modelsStatus, error: modelsError } = useModels("text");

  const [userSelectedModel, setUserSelectedModel] = useState("");
  const [context, setContext] = useState("");
  const [text, setText] = useState("");
  const [outcome, setOutcome] = useState<DemoOutcome>("success");
  const [inputError, setInputError] = useState<string | null>(null);

  const task = useDetectionTask();

  const isBusy =
    task.status === "starting" ||
    task.status === "queued" ||
    task.status === "processing";

  const selectedModel = models.some((m) => m.name === userSelectedModel)
    ? userSelectedModel
    : (models[0]?.name ?? "");

  const modelOptions = models.map((model) => ({
    value: model.name,
    label: `${model.name} v${model.version}`,
  }));

  const createTask = useCallback(() => {
    if (USE_MOCKS) {
      return mockCreateDetectionTask({
        modality: "text",
        model: selectedModel,
        outcome,
      });
    }
    return createTextDetection({ model: selectedModel, context, text });
  }, [selectedModel, context, text, outcome]);

  const handleSubmit = () => {
    if (isBusy) {
      return;
    }
    const trimmed = text.trim();
    if (trimmed.length < TEXT_MIN_LENGTH) {
      setInputError("Please enter some text to analyze before submitting.");
      return;
    }
    setInputError(null);
    task.begin(createTask);
  };

  const handleKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if ((event.metaKey || event.ctrlKey) && event.key === "Enter") {
      event.preventDefault();
      handleSubmit();
    }
  };

  const handleReset = () => {
    task.cancel();
  };

  const failureMessage = task.error ?? task.response?.error?.message ?? null;

  return (
    <div className="mx-auto max-w-2xl">
      <header className="mb-6">
        <h1 className="text-2xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-50">
          Text Detection
        </h1>
        <p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">
          Paste or type text to estimate whether it may have been generated by
          an AI model. Detection runs on the backend.
        </p>
      </header>

      {USE_MOCKS && <DemoControls outcome={outcome} onOutcomeChange={setOutcome} />}

      <Card className="mt-6 p-4 sm:p-5">
        <div className="mb-4">
          {modelsStatus === "loading" ? (
            <div className="flex items-center gap-2 text-sm text-zinc-500 dark:text-zinc-400">
              <Spinner /> Loading models…
            </div>
          ) : modelsStatus === "error" ? (
            <ErrorAlert message={modelsError ?? "Failed to load models."} />
          ) : models.length === 0 ? (
            <p className="text-sm text-zinc-500 dark:text-zinc-400">
              No text detection models are available.
            </p>
          ) : (
            <DetectionModelSelect
              model={selectedModel}
              onModelChange={setUserSelectedModel}
              modelOptions={modelOptions}
              disabled={isBusy}
            />
          )}
        </div>

        <label
          htmlFor="detection-text"
          className="mb-2 block text-sm font-medium text-zinc-700 dark:text-zinc-200"
        >
          Text to analyze
        </label>
        <textarea
          id="detection-text"
          value={text}
          onChange={(event) => setText(event.target.value)}
          rows={10}
          maxLength={TEXT_MAX_LENGTH}
          placeholder="Paste or type text here…"
          disabled={isBusy}
          onKeyDown={handleKeyDown}
          aria-describedby="text-help"
          className="w-full resize-y rounded-lg border border-zinc-300 bg-white px-3 py-2.5 text-sm text-zinc-900 placeholder:text-zinc-400 focus:border-indigo-500 focus:outline-2 focus:outline-indigo-500 disabled:cursor-not-allowed disabled:opacity-60 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100 dark:placeholder:text-zinc-500"
        />
        <div className="mt-1.5 flex items-center justify-between text-xs text-zinc-400 dark:text-zinc-500">
          <span id="text-help">Press Cmd/Ctrl + Enter to submit.</span>
          <span
            className={cn(
              text.length >= TEXT_MAX_LENGTH
                ? "font-medium text-amber-600 dark:text-amber-400"
                : undefined
            )}
          >
            {text.length} / {TEXT_MAX_LENGTH}
          </span>
        </div>
        <DetectionContextInput
          context={context}
          onContextChange={setContext}
          disabled={isBusy}
          className="mt-4"
        />
        {inputError && (
          <p role="alert" className="mt-2 text-sm text-red-600 dark:text-red-400">
            {inputError}
          </p>
        )}
      </Card>

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <Button
          onClick={handleSubmit}
          isLoading={isBusy}
          disabled={isBusy || modelsStatus !== "ready" || selectedModel === ""}
        >
          {task.status === "starting"
            ? "Submitting…"
            : isBusy
              ? "Analyzing…"
              : "Detect"}
        </Button>
        {isBusy && (
          <Button variant="ghost" onClick={task.cancel}>
            Cancel
          </Button>
        )}
        {(task.status === "completed" || task.status === "failed") && (
          <Button variant="ghost" onClick={handleReset}>
            Clear result
          </Button>
        )}
      </div>

      <div className="mt-6 space-y-3">
        {task.status === "starting" && (
          <div className="flex items-center gap-2 rounded-lg border border-zinc-200 bg-zinc-50 p-4 text-sm font-medium text-zinc-600 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300">
            <Spinner /> Submitting text…
          </div>
        )}
        {(task.status === "queued" || task.status === "processing") && (
          <DetectionStatus
            status={task.status}
            label={
              task.status === "queued" ? "Waiting in queue…" : "Analyzing…"
            }
          />
        )}
        {task.status === "completed" && task.response?.result && (
          <DetectionResult
            result={task.response.result}
            model={task.response.model}
            taskId={task.response.id}
          />
        )}
        {task.status === "failed" && failureMessage && (
          <ErrorAlert message={failureMessage} onDismiss={handleReset} />
        )}
      </div>
    </div>
  );
}