import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SiteNav } from "@/components/ui/SiteNav";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "AI-Generated Content Detector",
    template: "%s | AI-Generated Content Detector",
  },
  description:
    "Detect whether text, images, or videos may have been generated by AI.",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SiteNav />
        <main className="mx-auto w-full max-w-5xl flex-1 px-4 py-8 sm:px-6 sm:py-10">
          {children}
        </main>
        <footer className="border-t border-zinc-200 py-6 dark:border-zinc-800">
          <p className="mx-auto w-full max-w-5xl px-4 text-center text-sm text-zinc-500 dark:text-zinc-400 sm:px-6">
            AI-Generated Content Detector · Frontend demo — detection is
            performed by an external backend service.
          </p>
        </footer>
      </body>
    </html>
  );
}