import Link from "next/link";
import { Card } from "@/components/ui/Card";

const MODALITIES = [
  {
    href: "/text",
    title: "Text Detection",
    description:
      "Paste or type text and estimate whether it was likely written by an AI model.",
    icon: (
      <svg
        aria-hidden="true"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth={1.8}
        strokeLinecap="round"
        strokeLinejoin="round"
        className="size-6"
      >
        <path d="M9 12h6M9 16h4M5 5h8.5a1 1 0 0 1 .7.3l3.5 3.5a1 1 0 0 1 .3.7V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z" />
        <path d="M13.5 5v4.5H18" />
      </svg>
    ),
  },
  {
    href: "/image",
    title: "Image Detection",
    description:
      "Upload an image and estimate whether it may have been generated by AI.",
    icon: (
      <svg
        aria-hidden="true"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth={1.8}
        strokeLinecap="round"
        strokeLinejoin="round"
        className="size-6"
      >
        <rect x="3" y="5" width="18" height="14" rx="2" />
        <circle cx="8.5" cy="10" r="1.5" />
        <path d="m21 15-4-4c-.44-.44-1.16-.44-1.6 0L9 16" />
      </svg>
    ),
  },
  {
    href: "/video",
    title: "Video Detection",
    description:
      "Upload a video and follow an asynchronous analysis task to completion.",
    icon: (
      <svg
        aria-hidden="true"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth={1.8}
        strokeLinecap="round"
        strokeLinejoin="round"
        className="size-6"
      >
        <rect x="3" y="5" width="18" height="14" rx="2" />
        <path d="M7 5v14M17 5v14M3 9.5h4M3 14h4M17 9.5h4M17 14h4" />
      </svg>
    ),
  },
];

export default function Home() {
  return (
    <div className="mx-auto max-w-3xl">
      <section className="mt-4 text-center sm:mt-8">
        <span className="inline-block rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">
          Three detection modalities
        </span>
        <h1 className="mt-4 text-3xl font-semibold tracking-tight text-zinc-900 sm:text-4xl dark:text-zinc-50">
          AI-Generated Content Detector
        </h1>
        <p className="mx-auto mt-3 max-w-xl text-base text-zinc-600 dark:text-zinc-400">
          Choose a modality to estimate whether digital content may have been
          generated by an AI model. The analysis is performed by an external
          backend service.
        </p>
      </section>

      <section className="mt-8 grid gap-4 sm:mt-10 sm:grid-cols-2 lg:grid-cols-3">
        {MODALITIES.map((modality) => (
          <Link
            key={modality.href}
            href={modality.href}
            className="group focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500"
          >
            <Card className="flex h-full flex-col gap-3 p-5 transition-colors group-hover:border-indigo-300 dark:group-hover:border-indigo-700">
              <div className="flex size-12 items-center justify-center rounded-lg bg-indigo-50 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">
                {modality.icon}
              </div>
              <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-50">
                {modality.title}
              </h2>
              <p className="text-sm text-zinc-600 dark:text-zinc-400">
                {modality.description}
              </p>
              <span
                aria-hidden="true"
                className="mt-auto inline-flex items-center gap-1 text-sm font-medium text-indigo-600 dark:text-indigo-400"
              >
                Open
                <svg
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  className="size-4 transition-transform group-hover:translate-x-0.5"
                >
                  <path d="M6.28 5.22a.75.75 0 0 0 0 1.06L9.94 10l-3.66 3.72a.75.75 0 1 0 1.06 1.06l4.25-4.25a.75.75 0 0 0 0-1.06L8.34 5.22a.75.75 0 0 0-1.06 0Z" />
                </svg>
              </span>
            </Card>
          </Link>
        ))}
      </section>

      <aside className="mt-8 rounded-lg border border-zinc-200 bg-zinc-50 p-4 text-sm text-zinc-500 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-400">
        Detection results are model estimates rather than absolute proof. The
        UI always reports outcomes as likely AI-generated, likely
        human-generated, or uncertain.
      </aside>
    </div>
  );
}